version: '3'
services:
  web:
    build: ./web
    volumes:
      - ./web:/gallery/web
      - /gallery/web/node_modules
    ports:
      - 3000:3000
  server:
    build: ./server
    volumes:
      - ./server:/gallery/server
      - /gallery/server/node_modules
    ports:
      - 5000:5000
    depends_on:
      - web
    environment: 
      NODE_ENV: development